import { UserId, UserIdShort } from '@/components/contact/contact-form.types'

export const publicRoutes = [
  '/',
  '/api/webhooks/mailerlite', // TODO: secure it later!
  '/artistry-holistic-promo',
  '/available-slots',
  '/body-cleansing-program',
  '/c',
  '/e',
  '/e/be',
  '/e/bwb',
  '/e/de',
  '/e/de/20240616',
  '/e/de/n',
  '/e/de/next',
  '/e/diamond-event',
  '/e/diamond-event/n',
  '/e/diamond-event/next',
  '/e/dl',
  '/e/iac',
  '/e/pc',
  '/e/pc/20251010',
  '/e/pc/20260207',
  '/e/pc/n',
  '/e/pc/next',
  '/e/power-campus',
  '/e/power-campus/n',
  '/e/power-campus/next',
  '/events',
  '/events/be',
  '/events/biznes-espresso',
  '/events/breakfast-with-business',
  '/events/bwb',
  '/events/de',
  '/events/diamond-event',
  '/events/diamond-event/20240616',
  '/events/diamond-event/n',
  '/events/diamond-event/next',
  '/events/diamond-live',
  '/events/dl',
  '/events/iac',
  '/events/international-award-ceremony',
  '/events/pc',
  '/events/pc/next',
  '/events/power-campus/20251010',
  '/events/power-campus/20260207',
  '/events/power-campus/n',
  '/events/power-campus/next',
  '/generator-qr',
  '/i',
  '/invite',
  '/join',
  '/start',
  '/media/business-plan',
  '/ml/n8n-personal-response-contact-popup',
  '/mra-registration',
  '/mra-reports',
  '/pc',
  '/powercampus',
  '/products',
  '/products/artistry-holistic-promo',
  '/products/mra',
  '/products/mra/flyer',
  '/products/mra/registration',
  '/program',
  '/program/energy-program',
  '/tools/product-page-to-qrcode',
  `/c/${UserIdShort.MAREK_KUSTOSZ}/zoom`,
  `/c/${UserIdShort.MAREK_KUSTOSZ}`,
  `/c/${UserIdShort.SYLWIA_STACHOW}/zoom`,
  `/c/${UserIdShort.SYLWIA_STACHOW}`,
  `/contact/${UserId.MAREK_KUSTOSZ}/zoom`,
  `/contact/${UserId.MAREK_KUSTOSZ}`,
  `/contact/${UserId.SYLWIA_STACHOW}/zoom`,
  `/contact/${UserId.SYLWIA_STACHOW}`,
  '/wolne-terminy',
]

export const DEFAULT_REDIRECT = '/contact/marek-kustosz'

export const DEFAULT_LOGIN_REDIRECT = '/dashboard'

export const authRoutes = ['/auth/login', '/auth/register']

export const apiAuthPrefix = '/api/auth'
