export { default as PictogramProgram } from './pictogram-program-min.svg'
export { default as PictogramSociety } from './pictogram-society-min.svg'
export { default as PictogramPhone } from './pictogram-phone-min.svg'
export { default as ArtistryLogotype } from './artistry-logotype-min.svg'
export { default as WaQrMarekKustosz } from './wa-qr-code-mk.svg'
